version: 2.1

orbs:
  ruby: circleci/ruby@1.8.0
  node: circleci/node@5.0.2
  browser-tools: circleci/browser-tools@1.3.0

jobs:
  build:
    docker:
      # Specify the Ruby version you desire here
      - image: cimg/ruby:3.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: cimg/postgres:14.10
        environment:
          POSTGRES_USER: astuto
          POSTGRES_DB: project_name_test
          POSTGRES_PASSWORD: "dbpass"

    environment:
      BUNDLE_JOBS: "1"
      BUNDLE_RETRY: "1"
      PGHOST: 127.0.0.1
      PGUSER: circleci
      PGPASSWORD: ""
      RAILS_ENV: test
      CC_TEST_REPORTER_ID: some_long_token
      COVERAGE: true

    steps:
      - checkout
      - ruby/install-deps

      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # - run:
      #     name: Install Code Climate Test Reporter
      #     command: |
      #       curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #       chmod +x ./cc-test-reporter

      # - run:
      #     name: Test Setup
      #     command: |
      #       cp config/application.example.yml config/application.yml
      #       psql -U circleci -q -d project_name_test -f db/structure.sql -h localhost -p 5432
      #       bundle exec rake assets:precompile

      - run:
          name: Run Tests
          command: |
            bundle exec rspec --format progress

      # - run:
      #     name: Upload Test Results to Code Climate
      #     command: |
      #       ./cc-test-reporter format-coverage -t simplecov $CIRCLE_ARTIFACTS/coverage/.resultset.json
      #       ./cc-test-reporter upload-coverage

      # collect reports
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: test-results